### ISSUE TITLE
[Definição US] US21 - Categorização dos dados que alimentaração a base utlizando técnicas de machine learning.

### ISSUE THREAD

**Issue by guilherme-mendes** [fga-eps-mds/2021.1-PCTs-Docs#39]
## Descrição

Categorização dos dados que alimentaração a base utlizando técnicas de machine learning.

## Tarefas

- [x] Estruturação dos dados com classificação de **Territórios** enviados via docx.
- [x] Estruturação dos dados com classificações de **Território**, **Quilombolas**, **Identidade**, **Conflito** disponibilizados via forms.
- [x] Análise exploratória dos dados.
- [x] Treinamento do modelo classificador. 

## Critérios de aceitação

- [x] Obtenção de informações estruturadas e confiáveis para treinamento do modelo com uma boa acurácia.

## Issues relacionadas

Issues que compõe a User Story em questão, para considerá-la como concluída.
Essas issues são dividas em outros repositórios.

- [ ] [[Definição US] US21 - Categorização dos dados que alimentaração a base utlizando técnicas de machine learning](https://github.com/fga-eps-mds/2021.1-PCTs-ML-Training/issues/6)

**Comment by caiovfernandes** [comment]
## Issue finalizada no Pull Request:
[Model v1](https://github.com/fga-eps-mds/2021.1-PCTs-ML-Training/pull/5)
